### ISSUE TITLE
Errors starting locally

### ISSUE THREAD

**Issue by tiger5226** [lbryio/web-daemon#10]
I cloned and ran this repo as directed to run lbry.tech locally. Below is the result:

```
MacBookPro:web-daemon Mark$ npm run watch

> web-daemon@1.0.5 watch /Users/Mark/WebstormProjects/web-daemon
> micro-dev -w routes -p ${PORT:-5200}

micro: Error when importing /Users/Mark/WebstormProjects/web-daemon/index.js: TypeError: Environment file doesn't exist: /Users/Mark/WebstormProjects/web-daemon/.env
    at module.exports (/Users/Mark/WebstormProjects/web-daemon/node_modules/node-env-file/lib/index.js:130:19)
    at Object.<anonymous> (/Users/Mark/WebstormProjects/web-daemon/node_modules/vne/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Mark/WebstormProjects/web-daemon/routes/get/status.js:8:13)
micro: https://err.sh/micro/invalid-entry
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-daemon@1.0.5 watch: `micro-dev -w routes -p ${PORT:-5200}`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-daemon@1.0.5 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mark/.npm/_logs/2019-02-10T02_30_04_206Z-debug.log
```

There is no mention of a `.env` file in the readme. Is there something else I need to do to run this? 

I used webstorm 18.3 as the IDE.

**Comment by tiger5226** [comment]
I was able to copy the sample from the directory to get it running. We should add that to the readme.

**Comment by tzarebczan** [comment]
https://github.com/lbryio/web-daemon/pull/11
